# Generated by Django 4.1.3 on 2023-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_auto_20181112_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_book',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Год выхода'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
