# Generated by Django 4.1.3 on 2023-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0007_book_author_book_book_release_date_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_book',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Год выхода'),
            preserve_default=False,
        ),
    ]
