# Generated by Django 4.1.3 on 2023-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0008_alter_book_author_book_alter_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pages',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='codes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Исходный код'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Издательство'),
        ),
    ]
